frr defaults traditional
hostname r3
!
interface lo
 ip address 10.255.0.3/32
!
router rip
 version 2
 network 192.168.3.0/24
 network 10.0.23.0/29
 network 10.0.34.0/29
 network 10.0.13.0/29
 redistribute connected
 timers basic 5 15 20
!
line vty
!
