frr defaults traditional
hostname r3
!
interface lo
 ip address 10.255.0.3/32
!
router ospf
 ospf router-id 10.255.0.3
 network 192.168.3.0/24 area 0
 network 10.0.23.0/29 area 0
 network 10.0.34.0/29 area 0
 network 10.0.13.0/29 area 0
 network 10.255.0.3/32 area 0
!
line vty
!
